/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddCompsPanel.java
 *
 * Created on 28.08.2009, 15:01:28
 */

package reg.wizard.tlug.panels;

import java.util.Map;
import org.netbeans.spi.wizard.WizardController;

/**
 *
 * @author hbusch
 */
public class AddCompsPanel extends javax.swing.JPanel {

    private final WizardController controller;
    private final Map wizardData;

    /** Creates new form CatHairLengthPanel */
    public AddCompsPanel(WizardController controller, Map wizardData) {
        initComponents();

        this.controller = controller;
        this.wizardData = wizardData;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
