/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BaseDataPanel.java
 *
 * Created on 31.08.2009, 11:22:43
 */
package reg.wizard.tlug.panels;

import jams.io.JAMSFileFilter;
import java.io.File;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import org.h2.util.StringUtils;
import org.netbeans.spi.wizard.WizardController;

/**
 *
 * @author hbusch
 */
public class BaseDataPanel extends javax.swing.JPanel {

    private final WizardController controller;
    private final Map wizardData;
    private BaseDataPanel thisPanel;
    public static final String KEY_SHAPE_FILENAME = "shapeFileName";
    public static final String KEY_DATA_ORIGIN = "dataOrigin";
    public static final String KEY_REGIONALIZATION = "regionalizationData";
    public static final String KEY_INTERVAL = "interval";
    public static final String KEY_AGGR = "aggregation";
    public static final String VALUE_PRIM = "prim";
    public static final String VALUE_SEK = "sek";
    public static final String VALUE_TAG = "dd";
    public static final String VALUE_MON = "mm";
    public static final String VALUE_JAHR = "yy";

    // all field contents
    private String r_shapeFileName = null;
    private String r_dataOrigin = null;
    private String r_region = null;
    private String r_interval = null;
    private String r_aggreg = null;

    /** Creates new form  */
    public BaseDataPanel(WizardController controller, Map wizardData) {

        this.controller = controller;
        this.wizardData = wizardData;
        thisPanel = this;

        initComponents();
        setupComponents();

        jRadioButtonPrim.putClientProperty(KEY_DATA_ORIGIN, VALUE_PRIM);
        jRadioButtonSeku.putClientProperty(KEY_DATA_ORIGIN, VALUE_SEK);

        r_region = "Niederschlag"; // default

        jRadioButtonTag.putClientProperty(KEY_AGGR, VALUE_TAG);
        jRadioButtonMonat.putClientProperty(KEY_AGGR, VALUE_MON);
        jRadioButtonJahr.putClientProperty(KEY_AGGR, VALUE_JAHR);

        initFromWizardData();
        checkProblems();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFileLabel = new javax.swing.JLabel();
        jFileName = new javax.swing.JTextField();
        jFileButton = new javax.swing.JButton();
        jRegLabel = new javax.swing.JLabel();
        jRegCombo = new javax.swing.JComboBox();
        jRadioButtonPrim = new javax.swing.JRadioButton();
        jRadioButtonSeku = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonTag = new javax.swing.JRadioButton();
        jRadioButtonMonat = new javax.swing.JRadioButton();
        jRadioButtonJahr = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jIntervall = new javax.swing.JTextField();

        jFileLabel.setText("Shape-File");

        jFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileNameActionPerformed(evt);
            }
        });
        jFileName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFileNameFocusLost(evt);
            }
        });

        jFileButton.setText("Auswahl");
        jFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileButtonActionPerformed(evt);
            }
        });

        jRegLabel.setText("Regionalisierung von");

        jRegCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Niederschlag", "Tmin", "Tmax", "Tmean", "Feuchtigkeit" }));
        jRegCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegComboActionPerformed(evt);
            }
        });

        jRadioButtonPrim.setText("gemessen");
        jRadioButtonPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPrimActionPerformed(evt);
            }
        });

        jRadioButtonSeku.setText("abgeleitet");
        jRadioButtonSeku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSekuActionPerformed(evt);
            }
        });

        jLabel1.setText("Aggregierung");

        jRadioButtonTag.setText("Tag");
        jRadioButtonTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTagActionPerformed(evt);
            }
        });

        jRadioButtonMonat.setText("Monat");
        jRadioButtonMonat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMonatActionPerformed(evt);
            }
        });

        jRadioButtonJahr.setText("Jahr");
        jRadioButtonJahr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJahrActionPerformed(evt);
            }
        });

        jLabel2.setText("Datenherkunft");

        jLabel3.setText("Zeitintervall");

        jIntervall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIntervallActionPerformed(evt);
            }
        });
        jIntervall.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jIntervallFocusLost(evt);
            }
        });
        jIntervall.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jIntervallInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFileLabel)
                    .addComponent(jRegLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonTag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonMonat)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonJahr))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonPrim)
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButtonSeku))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFileButton))
                    .addComponent(jRegCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIntervall, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFileLabel)
                    .addComponent(jFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPrim)
                    .addComponent(jRadioButtonSeku)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRegLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRegCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jIntervall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButtonTag)
                    .addComponent(jRadioButtonMonat)
                    .addComponent(jRadioButtonJahr))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRegComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegComboActionPerformed
        // TODO add your handling code here:
        r_region = (String) jRegCombo.getSelectedItem();
        checkProblems();

}//GEN-LAST:event_jRegComboActionPerformed

    private void jRadioButtonMonatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMonatActionPerformed
        // TODO add your handling code here:
        aggregationSelected(evt);
}//GEN-LAST:event_jRadioButtonMonatActionPerformed

    private void jFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileNameActionPerformed

    private void jRadioButtonPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPrimActionPerformed
        // TODO add your handling code here:
        primSekSelected(evt);
    }//GEN-LAST:event_jRadioButtonPrimActionPerformed

    private void jRadioButtonSekuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSekuActionPerformed
        // TODO add your handling code here:
        primSekSelected(evt);
    }//GEN-LAST:event_jRadioButtonSekuActionPerformed

    private void jFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileButtonActionPerformed
        // TODO add your handling code here:
        String fileName = null;
        int returnVal = -1;
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(JAMSFileFilter.getShapeFilter());
        try {
            returnVal = chooser.showOpenDialog(thisPanel);
            File file = chooser.getSelectedFile();
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                fileName = file.getPath() + File.separator + file.getName();
                jFileName.setText(fileName);
            }

        } catch (Exception fnfexc) {
            fileName = null;
        }
        r_shapeFileName = fileName;
        checkProblems();
    }//GEN-LAST:event_jFileButtonActionPerformed

    private void jRadioButtonJahrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJahrActionPerformed
        // TODO add your handling code here:
        aggregationSelected(evt);
    }//GEN-LAST:event_jRadioButtonJahrActionPerformed

    private void jRadioButtonTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTagActionPerformed
        // TODO add your handling code here:
        aggregationSelected(evt);
    }//GEN-LAST:event_jRadioButtonTagActionPerformed

    private void jIntervallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIntervallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIntervallActionPerformed

    private void jIntervallInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jIntervallInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jIntervallInputMethodTextChanged

    private void jIntervallFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jIntervallFocusLost
        // TODO add your handling code here:
        r_interval = jIntervall.getText();
        checkProblems();

    }//GEN-LAST:event_jIntervallFocusLost

    private void jFileNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFileNameFocusLost
        // TODO add your handling code here:
        r_shapeFileName = jFileName.getText();
        checkProblems();
    }//GEN-LAST:event_jFileNameFocusLost

    private void setupComponents() {

        // group buttons
        buttonGroup1.add(jRadioButtonPrim);
        buttonGroup1.add(jRadioButtonSeku);

        buttonGroup2.add(jRadioButtonTag);
        buttonGroup2.add(jRadioButtonMonat);
        buttonGroup2.add(jRadioButtonJahr);

    }

    private void primSekSelected(java.awt.event.ActionEvent evt) {

        Object val = ((JRadioButton) evt.getSource()).getClientProperty(KEY_DATA_ORIGIN);
        r_dataOrigin = (String) val;
        checkProblems();

    }

    private void aggregationSelected(java.awt.event.ActionEvent evt) {

        Object val = ((JRadioButton) evt.getSource()).getClientProperty(KEY_AGGR);
        r_aggreg = (String) val;
        checkProblems();

    }

    private void checkProblems() {
        if (StringUtils.isNullOrEmpty(r_shapeFileName)) {
            controller.setProblem("Bitte Shape-File auswählen.");
        } else {
            wizardData.put(KEY_SHAPE_FILENAME, r_shapeFileName);
            if (StringUtils.isNullOrEmpty(r_dataOrigin)) {
                controller.setProblem("Bitte Datenherkunft auswählen.");
            } else {
                wizardData.put(KEY_DATA_ORIGIN, r_dataOrigin);
                if (StringUtils.isNullOrEmpty(r_region)) {
                    controller.setProblem("Bitte Regionalisierung festlegen.");
                } else {
                    wizardData.put(KEY_REGIONALIZATION, r_region);
                    if (StringUtils.isNullOrEmpty(r_interval)) {
                        controller.setProblem("Bitte Zeitintervall auswählen.");
                    } else {
                        wizardData.put(KEY_INTERVAL, r_interval);
                        if (StringUtils.isNullOrEmpty(r_aggreg)) {
                            controller.setProblem("Bitte Aggregation bestimmen.");
                        } else {
                            wizardData.put(KEY_AGGR, r_aggreg);
                            controller.setProblem(null);
                        }
                    }
                }
            }
        }
        return;
    }

    /**
     * init display data from wizard data
     */
    private void initFromWizardData() {
        
        String shapeFileName = (String) wizardData.get(KEY_SHAPE_FILENAME);
        if (!StringUtils.isNullOrEmpty(shapeFileName)) {
            r_shapeFileName = shapeFileName;
            jFileName.setText(r_shapeFileName);
        }
        String dataOrigin = (String) wizardData.get(KEY_DATA_ORIGIN);
        if (!StringUtils.isNullOrEmpty(dataOrigin)) {
            r_dataOrigin = dataOrigin;
            if (dataOrigin.equals(VALUE_PRIM))
                jRadioButtonPrim.setSelected(true);
            if (dataOrigin.equals(VALUE_SEK))
                jRadioButtonSeku.setSelected(true);
        }
        String regionalizationData = (String) wizardData.get(KEY_REGIONALIZATION);
        if (!StringUtils.isNullOrEmpty(regionalizationData)) {
            r_region = regionalizationData;
            jRegCombo.setSelectedItem(regionalizationData);
        }

        String interval = (String) wizardData.get(KEY_INTERVAL);
        if (!StringUtils.isNullOrEmpty(interval)) {
            r_interval = interval;
            jIntervall.setText(interval);
        }
        String aggregation = (String) wizardData.get(KEY_AGGR);
        if (!StringUtils.isNullOrEmpty(aggregation)) {
            r_aggreg = aggregation;
            if (aggregation.equals(VALUE_TAG))
                jRadioButtonTag.setSelected(true);
            if (aggregation.equals(VALUE_MON))
                jRadioButtonMonat.setSelected(true);
            if (aggregation.equals(VALUE_JAHR))
                jRadioButtonJahr.setSelected(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jFileButton;
    private javax.swing.JLabel jFileLabel;
    private javax.swing.JTextField jFileName;
    private javax.swing.JTextField jIntervall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonJahr;
    private javax.swing.JRadioButton jRadioButtonMonat;
    private javax.swing.JRadioButton jRadioButtonPrim;
    private javax.swing.JRadioButton jRadioButtonSeku;
    private javax.swing.JRadioButton jRadioButtonTag;
    private javax.swing.JComboBox jRegCombo;
    private javax.swing.JLabel jRegLabel;
    // End of variables declaration//GEN-END:variables
}
