/*
 * This is the first decision at wizard
 * spatial <-> station data
 */

package reg.wizard.tlug.panels;

import java.util.Map;
import javax.swing.JRadioButton;
import org.netbeans.spi.wizard.WizardController;

/**
 *
 * @author hbusch
 */
public class DataDecisionPanel extends javax.swing.JPanel {

    public static final String KEY_DATA = "data";
    public static final String VALUE_SPATIAL = "spatial";
    public static final String VALUE_STATION = "station";


    private final WizardController controller;
    private final Map wizardData;

    /** Creates new form SpeciesPanel */
    public DataDecisionPanel(WizardController controller, Map wizardData) {
        initComponents();
        this.controller = controller;
        this.wizardData = wizardData;

        //By default, nothing is selected
        controller.setProblem ("keine Datenart ausgewählt");

        //Associate the values with the radio buttons, so the event handler
        //can be very simple
        spatialButton.putClientProperty (KEY_DATA, VALUE_SPATIAL);
        stationButton.putClientProperty (KEY_DATA, VALUE_STATION);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    private void initComponents() {
        radioButtons = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        spatialButton = new javax.swing.JRadioButton();
        stationButton = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Was wollen Sie tun?");
        add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 12, 1, 1)));
        radioButtons.add(spatialButton);
        spatialButton.setText("räumliche Daten regionalisieren");
        spatialButton.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        spatialButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        spatialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speciesSelected(evt);
            }
        });

        jPanel1.add(spatialButton);

        radioButtons.add(stationButton);
        stationButton.setText("Stationsdaten generieren");
        stationButton.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(0, 0, 0, 0)));
        stationButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        stationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speciesSelected(evt);
            }
        });

        jPanel1.add(stationButton);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }


    private void speciesSelected(java.awt.event.ActionEvent evt) {
        JRadioButton button = (JRadioButton) evt.getSource();
        wizardData.put (KEY_DATA, button.getClientProperty(KEY_DATA));
        controller.setProblem(null);
        controller.setForwardNavigationMode(WizardController.MODE_CAN_CONTINUE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton spatialButton;
    private javax.swing.JRadioButton stationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup radioButtons;
    // End of variables declaration//GEN-END:variables


}
